---
title: Testing Astro
---

Public repo at https://github.com/brianwisti/rgb-astro-adoc

== What is this?

:adoc: https://asciidoctor.org
:adoc-js: https://github.com/asciidoctor/asciidoctor.js

It's {adoc}[Asciidoctor] in https://astro.build[Astro]!

****
This isn't a real draft post, but might become one later.
****

So far I've got:


- an `Asciidoctor` component using {adoc-js}[Asciidoctor.js]
- this file in `WORKSPACE/content/draft/testing-astro.adoc`
- a dynamic route that builds pages from files in `WORKSPACE/content/draft/*.adoc`
- the vanilla `asciidoctor.css` style rules, applied globally

== Notes so far

=== The `Asciidoctor` component

.`src/components/Asciidoctor.astro`
----
---
import Processor from 'asciidoctor';

let { content } = Astro.props;

if (!content) {
    content = "****\nNeed some content!\n****\n";
}

const htmlContent = Processor().convert(content);
---
<article>
    {htmlContent}
</article>
----

****
Huh.
Is this `include` not working because I'm getting it wrong?
Or is it because I'm on Windows?
****

----
include::src/components/Asciidoctor.astro[]
----

=== The `/draft` dynamic route

Doesn't need to be recursive, so it's the easiest one to start with.

.`src/pages/draft/[slug].astro`
----
---
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as process from 'node:process';

import matter from 'gray-matter';

import Asciidoctor from '../../components/Asciidoctor.astro';
import ArticleLayout from '../../layouts/ArticleLayout.astro';

export async function getStaticPaths() {
    const draftDir = path.join(
        process.cwd(), "content", "draft"
    );
    const adocDrafts = fs.readdirSync(draftDir)
        .filter((file) => path.extname(file) === ".adoc");

    return adocDrafts.map((file) => {
        const slug = path.basename(file, ".adoc");
        const filePath = path.join(draftDir, file);

        return {
            params: {
                slug: slug,
            },
            props: {
                filePath: filePath,
            },
        };
    });
}

const { slug } = Astro.request.params;
const { filePath } = Astro.props;

const article = matter.read(filePath);
const content = article.content;
const { title } = article.data;
---
<ArticleLayout title={title}>
    <Asciidoctor content={content} />
</ArticleLayout>
----

=== List Articles in a `SectionLayout`

Stealing and generalizing from my draft dynamic route.
Probably a good candidate for splitting into `packages/`.

----
---
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as process from 'node:process';

import matter from 'gray-matter';

import ArticleLayout from './ArticleLayout.astro';
import ArticleList from '../components/ArticleList.astro';

const { title, section } = Astro.props;
const sectionDir = path.join(
    process.cwd(), "content", section
);

const articles = fs.readdirSync(sectionDir)
    .filter((file) => path.extname(file) === ".adoc")
    .map((file) => {
        const slug = path.basename(file, ".adoc");
        const filePath = path.join(sectionDir, file);
        const article = matter.read(filePath);

        return {
            link: `/${section}/${slug}`,
            title: article.data.title,
        };
    })
    .sort((entry) => entry.title);
---
<ArticleLayout title={title}>
    <section><slot /></section>
    <ArticleList articles={articles} />
</ArticleLayout>
----

== A style component?

== Syntax highlighting for source code

== Routes for published content

NOTE: recursive dynamic routes

== Images