---
title: Testing Astro
---

Public repo at https://github.com/brianwisti/rgb-astro-adoc

== What is this?

:adoc: https://asciidoctor.org
:adoc-js: https://github.com/asciidoctor/asciidoctor.js

It's {adoc}[Asciidoctor] in https://astro.build[Astro]!

****
This isn't a real draft post, but might become one later.
****

So far I've got:


- an `Asciidoctor` component using {adoc-js}[Asciidoctor.js]
- this file in `WORKSPACE/content/draft/testing-astro.adoc`
- a dynamic route that builds pages from files in `WORKSPACE/content/draft/*.adoc`
- the vanilla `asciidoctor.css` style rules, applied globally

== Notes so far

.The `Asciidoctor` component
----
---
import Processor from 'asciidoctor';

let { content } = Astro.props;

if (!content) {
    content = "****\nNeed some content!\n****\n";
}

const htmlContent = Processor().convert(content);
---
<article>
    {htmlContent}
</article>
----

.`src/pages/draft/[slug].astro`
----
---
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

import matter from 'gray-matter';

import Asciidoctor from '../../components/Asciidoctor.astro';
import ArticleLayout from '../../layouts/ArticleLayout.astro';

export async function getStaticPaths() {
    const draftDir = path.join(
        process.cwd(), "content", "draft"
    );
    const adocDrafts = fs.readdirSync(draftDir)
        .filter((file) => path.extname(file) === ".adoc");

    return adocDrafts.map((file) => {
        const slug = path.basename(file, ".adoc");
        const filePath = path.join(draftDir, file);

        return {
            params: {
                slug: slug,
            },
            props: {
                filePath: filePath,
            },
        };
    });
}

const { slug } = Astro.request.params;
const { filePath } = Astro.props;

const article = matter.read(filePath);
const content = article.content;
const { title } = article.data;
---
<ArticleLayout title={title}>
    <Asciidoctor content={content} />
</ArticleLayout>
----

=== `AdocDraftLayout`

Nothing too complicated.
Use `BaseLayout` with an Asciidoctor component for the slot.

=== The dynamic routes file

== Prefer `asciidoctor-html5s`

never mind.
It doesn't play well with my tiny understanding of `import` semantics.

Oh well.
Let's make some progress here before busting out pandoc and porting everything to yet another format.

== A style component?

== Syntax highlighting for source code

== Routes for published content

NOTE: recursive dynamic routes

== Images